### ISSUE TITLE
replace http-server or figure out fix to  "Corrupted content error"

### ISSUE THREAD

**Issue by titaniumbones** [DigitalHistory/advanced-topics#27]
http-server has a [longstanding bug](https://github.com/http-party/http-server/issues/525), apparently in its service-worker, which leads to angry browsers displaying a "corrupted content" or ERR_INVALID_REDIRECT. It's possible tat downgrading to http_server 0.9.0 will fix the problem, or downgrading the ecstatic dependency manually to something below 4.1.3.  Bt... I have't made it work myself yet. An alternative is to use `local-web-server` instead.

**Comment by thornjad** [comment]
Is this a Windows-only issue like http-party/http-server#525?

**Comment by titaniumbones** [comment]
I don't think so.  In any case updating dependencies seems to fixed it.

**Comment by titaniumbones** [comment]
Reopening as I'm seeing what appears to be the same issue back again on firefox at least (not on chrome)
